// Copyright (c) 2014, J. Salvador Arias <jsalarias@csnat.unt.edu.ar>
// All rights reserved.
// Distributed under BSD2 license that can be found in the LICENSE file.

package geography

// Country is a valid iso 3166-1 alpha-2 county code.
type Country string

// GetCountry returns a country code from a country name or code.
func GetCountry(name string) Country {
	c, ok := codeCountry[name]
	if !ok {
		return ""
	}
	return c
}

// Name returns the name of a country code.
func (c Country) Name() string {
	name, ok := country[c]
	if !ok {
		return ""
	}
	return name
}

var codeCountry = map[string]Country{
	"Andorra":              "AD",
	"United Arab Emirates": "AE",
	"UAE":                    "AE",
	"Afghanistan":            "AF",
	"Antigua and Barbuda":    "AG",
	"Antigua":                "AG",
	"Anguilla":               "AI",
	"Albania":                "AL",
	"Armenia":                "AM",
	"Angola":                 "AO",
	"Antarctica":             "AQ",
	"Argentina":              "AR",
	"American Samoa":         "AS",
	"Austria":                "AT",
	"Australia":              "AU",
	"Aruba":                  "AW",
	"Åland Islands":          "AX",
	"Aland Islands":          "AX",
	"Åland":                  "AX",
	"Aland":                  "AX",
	"Azerbaijan":             "AZ",
	"Bosnia and Herzegovina": "BA",
	"Bosnia":                 "BA",
	"Barbados":               "BB",
	"Bangladesh":             "BD",
	"Belgium":                "BE",
	"Burkina Faso":           "BF",
	"Bulgaria":               "BG",
	"Bahrain":                "BH",
	"Burundi":                "BI",
	"Benin":                  "BJ",
	"Saint Barthélemy":       "BL",
	"Saint Barthelemy":       "BL",
	"Bermuda":                "BM",
	"Brunei Darussalam":      "BN",
	"Brunei":                 "BN",
	"Bolivia, Plurinational State of":  "BO",
	"Bolivia":                          "BO",
	"Bonaire, Sint Eustatius and Saba": "BQ",
	"Bonaire":                          "BQ",
	"Brazil":                           "BR",
	"Bahamas":                          "BS",
	"Bhutan":                           "BT",
	"Bouvet Island":                    "BV",
	"Bouvet":                           "BV",
	"Botswana":                         "BW",
	"Belarus":                          "BY",
	"Belize":                           "BZ",
	"Canada":                           "CA",
	"Cocos (Keeling) Islands":          "CC",
	"Cocos Islands":                    "CC",
	"Keeling Islands":                  "CC",
	"Cocos":                            "CC",
	"Keeling":                          "CC",
	"Congo, the Democratic Republic of the": "CD",
	"DR Congo":                              "CD",
	"RDC":                                   "CD",
	"Central African Republic": "CF",
	"Congo":                    "CG",
	"Switzerland":              "CH",
	"Côte d'Ivoire":            "CI",
	"Cote d'Ivoire":            "CI",
	"Cook Islands":             "CK",
	"Cook":                     "CK",
	"Chile":                    "CL",
	"Cameroon":                 "CM",
	"China":                    "CN",
	"Colombia":                 "CO",
	"Costa Rica":               "CR",
	"Cuba":                     "CU",
	"Cape Verde":               "CV",
	"Curaçao":                  "CW",
	"Curacao":                  "CW",
	"Christmas Island":         "CX",
	"Christmas":                "CX",
	"Cyprus":                   "CY",
	"Czech Republic":           "CZ",
	"Czech":                    "CZ",
	"Germany":                  "DE",
	"Djibouti":                 "DJ",
	"Denmark":                  "DK",
	"Dominica":                 "DM",
	"Dominican Republic":       "DO",
	"Algeria":                  "DZ",
	"Ecuador":                  "EC",
	"Estonia":                  "EE",
	"Egypt":                    "EG",
	"Western Sahara":           "EH",
	"Eritrea":                  "ER",
	"Spain":                    "ES",
	"Ethiopia":                 "ET",
	"Finland":                  "FI",
	"Fiji":                     "FJ",
	"Falkland Islands (Malvinas)":     "FK",
	"Falkland Islands":                "FK",
	"Falkland":                        "FK",
	"Malvinas":                        "FK",
	"Micronesia, Federated States of": "FM",
	"Micronesia":                      "FM",
	"Faroe Islands":                   "FO",
	"Faroe":                           "FO",
	"France":                          "FR",
	"Gabon":                           "GA",
	"United Kingdom":                  "GB",
	"UK":                              "GB",
	"Great Britain":                   "GB",
	"Britain":                         "GB",
	"Grenada":                         "GD",
	"Georgia":                         "GE",
	"French Guiana":                   "GF",
	"Guernsey":                        "GG",
	"Ghana":                           "GH",
	"Gibraltar":                       "GI",
	"Greenland":                       "GL",
	"Gambia":                          "GM",
	"Guinea":                          "GN",
	"Guadeloupe":                      "GP",
	"Equatorial Guinea":               "GQ",
	"Greece":                          "GR",
	"South Georgia and the South Sandwich Islands": "GS",
	"South Georgia":                                "GS",
	"Guatemala":                                    "GT",
	"Guam":                                         "GU",
	"Guinea-Bissau":                                "GW",
	"Guyana":                                       "GY",
	"Hong Kong":                                    "HK",
	"Heard Island and McDonald Islands":            "HM",
	"Heard Island":                                 "HM",
	"Heard":                                        "HM",
	"Honduras":                                     "HN",
	"Croatia":                                      "HR",
	"Haiti":                                        "HT",
	"Hungary":                                      "HU",
	"Indonesia":                                    "ID",
	"Ireland":                                      "IE",
	"Israel":                                       "IL",
	"Isle of Man":                                  "IM",
	"Man":                                          "IM",
	"India":                                        "IN",
	"British Indian Ocean Territory": "IO",
	"Iraq": "IQ",
	"Iran, Islamic Republic of": "IR",
	"Iran":                                   "IR",
	"Iceland":                                "IS",
	"Italy":                                  "IT",
	"Jersey":                                 "JE",
	"Jamaica":                                "JM",
	"Jordan":                                 "JO",
	"Japan":                                  "JP",
	"Kenya":                                  "KE",
	"Kyrgyzstan":                             "KG",
	"Cambodia":                               "KH",
	"Kiribati":                               "KI",
	"Comoros":                                "KM",
	"Saint Kitts and Nevis":                  "KN",
	"Saint Kitts":                            "KN",
	"Korea, Democratic People's Republic of": "KP",
	"DPRK":                             "KP",
	"Korea, Republic of":               "KR",
	"Kuwait":                           "KW",
	"Cayman Islands":                   "KY",
	"Cayman":                           "KY",
	"Kazakhstan":                       "KZ",
	"Lao People's Democratic Republic": "LA",
	"Laos":                                       "LA",
	"Lebanon":                                    "LB",
	"Saint Lucia":                                "LC",
	"Liechtenstein":                              "LI",
	"Sri Lanka":                                  "LK",
	"Liberia":                                    "LR",
	"Lesotho":                                    "LS",
	"Lithuania":                                  "LT",
	"Luxembourg":                                 "LU",
	"Latvia":                                     "LV",
	"Libya":                                      "LY",
	"Morocco":                                    "MA",
	"Monaco":                                     "MC",
	"Moldova, Republic of":                       "MD",
	"Moldova":                                    "MD",
	"Montenegro":                                 "ME",
	"Saint Martin (French part)":                 "MF",
	"Saint Martin":                               "MF",
	"Madagascar":                                 "MG",
	"Marshall Islands":                           "MH",
	"Macedonia, the former Yugoslav Republic of": "MK",
	"Macedonia":                 "MK",
	"Mali":                      "ML",
	"Myanmar":                   "MM",
	"Mongolia":                  "MN",
	"Macao":                     "MO",
	"Northern Mariana Islands":  "MP",
	"Martinique":                "MQ",
	"Mauritania":                "MR",
	"Montserrat":                "MS",
	"Malta":                     "MT",
	"Mauritius":                 "MU",
	"Maldives":                  "MV",
	"Malawi":                    "MW",
	"Mexico":                    "MX",
	"Malaysia":                  "MY",
	"Mozambique":                "MZ",
	"Namibia":                   "NA",
	"New Caledonia":             "NC",
	"Niger":                     "NE",
	"Norfolk Island":            "NF",
	"Norfolk":                   "NF",
	"Nigeria":                   "NG",
	"Nicaragua":                 "NI",
	"Netherlands":               "NL",
	"Norway":                    "NO",
	"Nepal":                     "NP",
	"Nauru":                     "NR",
	"Niue":                      "NU",
	"New Zealand":               "NZ",
	"Oman":                      "OM",
	"Panama":                    "PA",
	"Peru":                      "PE",
	"French Polynesia":          "PF",
	"Papua New Guinea":          "PG",
	"Philippines":               "PH",
	"Pakistan":                  "PK",
	"Poland":                    "PL",
	"Saint Pierre and Miquelon": "PM",
	"Saint Pierre":              "PM",
	"Pitcairn":                  "PN",
	"Puerto Rico":               "PR",
	"Palestine, State of":       "PS",
	"Palestine":                 "PS",
	"Portugal":                  "PT",
	"Palau":                     "PW",
	"Paraguay":                  "PY",
	"Qatar":                     "QA",
	"Réunion":                   "RE",
	"Reunion":                   "RE",
	"Romania":                   "RO",
	"Serbia":                    "RS",
	"Russian Federation":        "RU",
	"Russia":                    "RU",
	"Rwanda":                    "RW",
	"Saudi Arabia":              "SA",
	"Solomon Islands":           "SB",
	"Solomon":                   "SB",
	"Seychelles":                "SC",
	"Sudan":                     "SD",
	"Sweden":                    "SE",
	"Singapore":                 "SG",
	"Saint Helena, Ascension and Tristan da Cunha": "SH",
	"Saint Helena":                                 "SH",
	"Slovenia":                                     "SI",
	"Svalbard and Jan Mayen":                       "SJ",
	"Svalbard":                                     "SJ",
	"Slovakia":                                     "SK",
	"Sierra Leone":                                 "SL",
	"San Marino":                                   "SM",
	"Senegal":                                      "SN",
	"Somalia":                                      "SO",
	"Suriname":                                     "SR",
	"South Sudan":                                  "SS",
	"Sao Tome and Principe":                        "ST",
	"Sao Tome":                                     "ST",
	"El Salvador":                                  "SV",
	"Sint Maarten (Dutch part)":                    "SX",
	"Sint Maarten":                                 "SX",
	"Syrian Arab Republic":                         "SY",
	"Syria":                                        "SY",
	"Swaziland":                                    "SZ",
	"Turks and Caicos Islands":                     "TC",
	"Chad": "TD",
	"French Southern Territories": "TF",
	"Togo":                         "TG",
	"Thailand":                     "TH",
	"Tajikistan":                   "TJ",
	"Tokelau":                      "TK",
	"Timor-Leste":                  "TL",
	"Timor":                        "TL",
	"Turkmenistan":                 "TM",
	"Tunisia":                      "TN",
	"Tonga":                        "TO",
	"Turkey":                       "TR",
	"Trinidad and Tobago":          "TT",
	"Tuvalu":                       "TV",
	"Taiwan, Province of China":    "TW",
	"Taiwan":                       "TW",
	"Tanzania, United Republic of": "TZ",
	"Tanzania":                     "TZ",
	"Ukraine":                      "UA",
	"Uganda":                       "UG",
	"United States Minor Outlying Islands": "UM",
	"United States":                        "US",
	"USA":                                  "US",
	"Uruguay":                              "UY",
	"Uzbekistan":                           "UZ",
	"Holy See (Vatican City State)":        "VA",
	"Holy See":                             "VA",
	"Vatican City State":                   "VA",
	"Vatican":                              "VA",
	"Saint Vincent and the Grenadines":     "VC",
	"Saint Vincent":                        "VC",
	"Venezuela, Bolivarian Republic of":    "VE",
	"Venezuela":                            "VE",
	"Virgin Islands, British":              "VG",
	"Virgin Islands, U.S.":                 "VI",
	"Viet Nam":                             "VN",
	"Vanuatu":                              "VU",
	"Wallis and Futuna":                    "WF",
	"Wallis":                               "WF",
	"Samoa":                                "WS",
	"Yemen":                                "YE",
	"Mayotte":                              "YT",
	"South Africa":                         "ZA",
	"Zambia":                               "ZM",
	"Zimbabwe":                             "ZW",
	"AD":                                   "AD",
	"AE":                                   "AE",
	"AF":                                   "AF",
	"AG":                                   "AG",
	"AI":                                   "AI",
	"AL":                                   "AL",
	"AM":                                   "AM",
	"AO":                                   "AO",
	"AQ":                                   "AQ",
	"AR":                                   "AR",
	"AS":                                   "AS",
	"AT":                                   "AT",
	"AU":                                   "AU",
	"AW":                                   "AW",
	"AX":                                   "AX",
	"AZ":                                   "AZ",
	"BA":                                   "BA",
	"BB":                                   "BB",
	"BD":                                   "BD",
	"BE":                                   "BE",
	"BF":                                   "BF",
	"BG":                                   "BG",
	"BH":                                   "BH",
	"BI":                                   "BI",
	"BJ":                                   "BJ",
	"BL":                                   "BL",
	"BM":                                   "BM",
	"BN":                                   "BN",
	"BO":                                   "BO",
	"BQ":                                   "BQ",
	"BR":                                   "BR",
	"BS":                                   "BS",
	"BT":                                   "BT",
	"BV":                                   "BV",
	"BW":                                   "BW",
	"BY":                                   "BY",
	"BZ":                                   "BZ",
	"CA":                                   "CA",
	"CC":                                   "CC",
	"CD":                                   "CD",
	"CF":                                   "CF",
	"CG":                                   "CG",
	"CH":                                   "CH",
	"CI":                                   "CI",
	"CK":                                   "CK",
	"CL":                                   "CL",
	"CM":                                   "CM",
	"CN":                                   "CN",
	"CO":                                   "CO",
	"CR":                                   "CR",
	"CU":                                   "CU",
	"CV":                                   "CV",
	"CW":                                   "CW",
	"CX":                                   "CX",
	"CY":                                   "CY",
	"CZ":                                   "CZ",
	"DE":                                   "DE",
	"DJ":                                   "DJ",
	"DK":                                   "DK",
	"DM":                                   "DM",
	"DO":                                   "DO",
	"DZ":                                   "DZ",
	"EC":                                   "EC",
	"EE":                                   "EE",
	"EG":                                   "EG",
	"EH":                                   "EH",
	"ER":                                   "ER",
	"ES":                                   "ES",
	"ET":                                   "ET",
	"FI":                                   "FI",
	"FJ":                                   "FJ",
	"FK":                                   "FK",
	"FM":                                   "FM",
	"FO":                                   "FO",
	"FR":                                   "FR",
	"GA":                                   "GA",
	"GB":                                   "GB",
	"GD":                                   "GD",
	"GE":                                   "GE",
	"GF":                                   "GF",
	"GG":                                   "GG",
	"GH":                                   "GH",
	"GI":                                   "GI",
	"GL":                                   "GL",
	"GM":                                   "GM",
	"GN":                                   "GN",
	"GP":                                   "GP",
	"GQ":                                   "GQ",
	"GR":                                   "GR",
	"GS":                                   "GS",
	"GT":                                   "GT",
	"GU":                                   "GU",
	"GW":                                   "GW",
	"GY":                                   "GY",
	"HK":                                   "HK",
	"HM":                                   "HM",
	"HN":                                   "HN",
	"HR":                                   "HR",
	"HT":                                   "HT",
	"HU":                                   "HU",
	"ID":                                   "ID",
	"IE":                                   "IE",
	"IL":                                   "IL",
	"IM":                                   "IM",
	"IN":                                   "IN",
	"IO":                                   "IO",
	"IQ":                                   "IQ",
	"IR":                                   "IR",
	"IS":                                   "IS",
	"IT":                                   "IT",
	"JE":                                   "JE",
	"JM":                                   "JM",
	"JO":                                   "JO",
	"JP":                                   "JP",
	"KE":                                   "KE",
	"KG":                                   "KG",
	"KH":                                   "KH",
	"KI":                                   "KI",
	"KM":                                   "KM",
	"KN":                                   "KN",
	"KP":                                   "KP",
	"KR":                                   "KR",
	"KW":                                   "KW",
	"KY":                                   "KY",
	"KZ":                                   "KZ",
	"LA":                                   "LA",
	"LB":                                   "LB",
	"LC":                                   "LC",
	"LI":                                   "LI",
	"LK":                                   "LK",
	"LR":                                   "LR",
	"LS":                                   "LS",
	"LT":                                   "LT",
	"LU":                                   "LU",
	"LV":                                   "LV",
	"LY":                                   "LY",
	"MA":                                   "MA",
	"MC":                                   "MC",
	"MD":                                   "MD",
	"ME":                                   "ME",
	"MF":                                   "MF",
	"MG":                                   "MG",
	"MH":                                   "MH",
	"MK":                                   "MK",
	"ML":                                   "ML",
	"MM":                                   "MM",
	"MN":                                   "MN",
	"MO":                                   "MO",
	"MP":                                   "MP",
	"MQ":                                   "MQ",
	"MR":                                   "MR",
	"MS":                                   "MS",
	"MT":                                   "MT",
	"MU":                                   "MU",
	"MV":                                   "MV",
	"MW":                                   "MW",
	"MX":                                   "MX",
	"MY":                                   "MY",
	"MZ":                                   "MZ",
	"NA":                                   "NA",
	"NC":                                   "NC",
	"NE":                                   "NE",
	"NF":                                   "NF",
	"NG":                                   "NG",
	"NI":                                   "NI",
	"NL":                                   "NL",
	"NO":                                   "NO",
	"NP":                                   "NP",
	"NR":                                   "NR",
	"NU":                                   "NU",
	"NZ":                                   "NZ",
	"OM":                                   "OM",
	"PA":                                   "PA",
	"PE":                                   "PE",
	"PF":                                   "PF",
	"PG":                                   "PG",
	"PH":                                   "PH",
	"PK":                                   "PK",
	"PL":                                   "PL",
	"PM":                                   "PM",
	"PN":                                   "PN",
	"PR":                                   "PR",
	"PS":                                   "PS",
	"PT":                                   "PT",
	"PW":                                   "PW",
	"PY":                                   "PY",
	"QA":                                   "QA",
	"RE":                                   "RE",
	"RO":                                   "RO",
	"RS":                                   "RS",
	"RU":                                   "RU",
	"RW":                                   "RW",
	"SA":                                   "SA",
	"SB":                                   "SB",
	"SC":                                   "SC",
	"SD":                                   "SD",
	"SE":                                   "SE",
	"SG":                                   "SG",
	"SH":                                   "SH",
	"SI":                                   "SI",
	"SJ":                                   "SJ",
	"SK":                                   "SK",
	"SL":                                   "SL",
	"SM":                                   "SM",
	"SN":                                   "SN",
	"SO":                                   "SO",
	"SR":                                   "SR",
	"SS":                                   "SS",
	"ST":                                   "ST",
	"SV":                                   "SV",
	"SX":                                   "SX",
	"SY":                                   "SY",
	"SZ":                                   "SZ",
	"TC":                                   "TC",
	"TD":                                   "TD",
	"TF":                                   "TF",
	"TG":                                   "TG",
	"TH":                                   "TH",
	"TJ":                                   "TJ",
	"TK":                                   "TK",
	"TL":                                   "TL",
	"TM":                                   "TM",
	"TN":                                   "TN",
	"TO":                                   "TO",
	"TR":                                   "TR",
	"TT":                                   "TT",
	"TV":                                   "TV",
	"TW":                                   "TW",
	"TZ":                                   "TZ",
	"UA":                                   "UA",
	"UG":                                   "UG",
	"UM":                                   "UM",
	"US":                                   "US",
	"UY":                                   "UY",
	"UZ":                                   "UZ",
	"VA":                                   "VA",
	"VC":                                   "VC",
	"VE":                                   "VE",
	"VG":                                   "VG",
	"VI":                                   "VI",
	"VN":                                   "VN",
	"VU":                                   "VU",
	"WF":                                   "WF",
	"WS":                                   "WS",
	"YE":                                   "YE",
	"YT":                                   "YT",
	"ZA":                                   "ZA",
	"ZM":                                   "ZM",
	"ZW":                                   "ZW",
}

var country = map[Country]string{
	"AD": "Andorra",
	"AE": "United Arab Emirates",
	"AF": "Afghanistan",
	"AG": "Antigua and Barbuda",
	"AI": "Anguilla",
	"AL": "Albania",
	"AM": "Armenia",
	"AO": "Angola",
	"AQ": "Antarctica",
	"AR": "Argentina",
	"AS": "American Samoa",
	"AT": "Austria",
	"AU": "Australia",
	"AW": "Aruba",
	"AX": "Åland Islands",
	"AZ": "Azerbaijan",
	"BA": "Bosnia and Herzegovina",
	"BB": "Barbados",
	"BD": "Bangladesh",
	"BE": "Belgium",
	"BF": "Burkina Faso",
	"BG": "Bulgaria",
	"BH": "Bahrain",
	"BI": "Burundi",
	"BJ": "Benin",
	"BL": "Saint Barthélemy",
	"BM": "Bermuda",
	"BN": "Brunei Darussalam",
	"BO": "Bolivia, Plurinational State of",
	"BQ": "Bonaire, Sint Eustatius and Saba",
	"BR": "Brazil",
	"BS": "Bahamas",
	"BT": "Bhutan",
	"BV": "Bouvet Island",
	"BW": "Botswana",
	"BY": "Belarus",
	"BZ": "Belize",
	"CA": "Canada",
	"CC": "Cocos (Keeling) Islands",
	"CD": "Congo, the Democratic Republic of the",
	"CF": "Central African Republic",
	"CG": "Congo",
	"CH": "Switzerland",
	"CI": "Côte d'Ivoire",
	"CK": "Cook Islands",
	"CL": "Chile",
	"CM": "Cameroon",
	"CN": "China",
	"CO": "Colombia",
	"CR": "Costa Rica",
	"CU": "Cuba",
	"CV": "Cape Verde",
	"CW": "Curaçao",
	"CX": "Christmas Island",
	"CY": "Cyprus",
	"CZ": "Czech Republic",
	"DE": "Germany",
	"DJ": "Djibouti",
	"DK": "Denmark",
	"DM": "Dominica",
	"DO": "Dominican Republic",
	"DZ": "Algeria",
	"EC": "Ecuador",
	"EE": "Estonia",
	"EG": "Egypt",
	"EH": "Western Sahara",
	"ER": "Eritrea",
	"ES": "Spain",
	"ET": "Ethiopia",
	"FI": "Finland",
	"FJ": "Fiji",
	"FK": "Falkland Islands (Malvinas)",
	"FM": "Micronesia, Federated States of",
	"FO": "Faroe Islands",
	"FR": "France",
	"GA": "Gabon",
	"GB": "United Kingdom",
	"GD": "Grenada",
	"GE": "Georgia",
	"GF": "French Guiana",
	"GG": "Guernsey",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GL": "Greenland",
	"GM": "Gambia",
	"GN": "Guinea",
	"GP": "Guadeloupe",
	"GQ": "Equatorial Guinea",
	"GR": "Greece",
	"GS": "South Georgia and the South Sandwich Islands",
	"GT": "Guatemala",
	"GU": "Guam",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HK": "Hong Kong",
	"HM": "Heard Island and McDonald Islands",
	"HN": "Honduras",
	"HR": "Croatia",
	"HT": "Haiti",
	"HU": "Hungary",
	"ID": "Indonesia",
	"IE": "Ireland",
	"IL": "Israel",
	"IM": "Isle of Man",
	"IN": "India",
	"IO": "British Indian Ocean Territory",
	"IQ": "Iraq",
	"IR": "Iran, Islamic Republic of",
	"IS": "Iceland",
	"IT": "Italy",
	"JE": "Jersey",
	"JM": "Jamaica",
	"JO": "Jordan",
	"JP": "Japan",
	"KE": "Kenya",
	"KG": "Kyrgyzstan",
	"KH": "Cambodia",
	"KI": "Kiribati",
	"KM": "Comoros",
	"KN": "Saint Kitts and Nevis",
	"KP": "Korea, Democratic People's Republic of",
	"KR": "Korea, Republic of",
	"KW": "Kuwait",
	"KY": "Cayman Islands",
	"KZ": "Kazakhstan",
	"LA": "Lao People's Democratic Republic",
	"LB": "Lebanon",
	"LC": "Saint Lucia",
	"LI": "Liechtenstein",
	"LK": "Sri Lanka",
	"LR": "Liberia",
	"LS": "Lesotho",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"LV": "Latvia",
	"LY": "Libya",
	"MA": "Morocco",
	"MC": "Monaco",
	"MD": "Moldova, Republic of",
	"ME": "Montenegro",
	"MF": "Saint Martin (French part)",
	"MG": "Madagascar",
	"MH": "Marshall Islands",
	"MK": "Macedonia, the former Yugoslav Republic of",
	"ML": "Mali",
	"MM": "Myanmar",
	"MN": "Mongolia",
	"MO": "Macao",
	"MP": "Northern Mariana Islands",
	"MQ": "Martinique",
	"MR": "Mauritania",
	"MS": "Montserrat",
	"MT": "Malta",
	"MU": "Mauritius",
	"MV": "Maldives",
	"MW": "Malawi",
	"MX": "Mexico",
	"MY": "Malaysia",
	"MZ": "Mozambique",
	"NA": "Namibia",
	"NC": "New Caledonia",
	"NE": "Niger",
	"NF": "Norfolk Island",
	"NG": "Nigeria",
	"NI": "Nicaragua",
	"NL": "Netherlands",
	"NO": "Norway",
	"NP": "Nepal",
	"NR": "Nauru",
	"NU": "Niue",
	"NZ": "New Zealand",
	"OM": "Oman",
	"PA": "Panama",
	"PE": "Peru",
	"PF": "French Polynesia",
	"PG": "Papua New Guinea",
	"PH": "Philippines",
	"PK": "Pakistan",
	"PL": "Poland",
	"PM": "Saint Pierre and Miquelon",
	"PN": "Pitcairn",
	"PR": "Puerto Rico",
	"PS": "Palestine, State of",
	"PT": "Portugal",
	"PW": "Palau",
	"PY": "Paraguay",
	"QA": "Qatar",
	"RE": "Réunion",
	"RO": "Romania",
	"RS": "Serbia",
	"RU": "Russian Federation",
	"RW": "Rwanda",
	"SA": "Saudi Arabia",
	"SB": "Solomon Islands",
	"SC": "Seychelles",
	"SD": "Sudan",
	"SE": "Sweden",
	"SG": "Singapore",
	"SH": "Saint Helena, Ascension and Tristan da Cunha",
	"SI": "Slovenia",
	"SJ": "Svalbard and Jan Mayen",
	"SK": "Slovakia",
	"SL": "Sierra Leone",
	"SM": "San Marino",
	"SN": "Senegal",
	"SO": "Somalia",
	"SR": "Suriname",
	"SS": "South Sudan",
	"ST": "Sao Tome and Principe",
	"SV": "El Salvador",
	"SX": "Sint Maarten (Dutch part)",
	"SY": "Syrian Arab Republic",
	"SZ": "Swaziland",
	"TC": "Turks and Caicos Islands",
	"TD": "Chad",
	"TF": "French Southern Territories",
	"TG": "Togo",
	"TH": "Thailand",
	"TJ": "Tajikistan",
	"TK": "Tokelau",
	"TL": "Timor-Leste",
	"TM": "Turkmenistan",
	"TN": "Tunisia",
	"TO": "Tonga",
	"TR": "Turkey",
	"TT": "Trinidad and Tobago",
	"TV": "Tuvalu",
	"TW": "Taiwan, Province of China",
	"TZ": "Tanzania, United Republic of",
	"UA": "Ukraine",
	"UG": "Uganda",
	"UM": "United States Minor Outlying Islands",
	"US": "United States",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VA": "Holy See (Vatican City State)",
	"VC": "Saint Vincent and the Grenadines",
	"VE": "Venezuela, Bolivarian Republic of",
	"VG": "Virgin Islands, British",
	"VI": "Virgin Islands, U.S.",
	"VN": "Viet Nam",
	"VU": "Vanuatu",
	"WF": "Wallis and Futuna",
	"WS": "Samoa",
	"YE": "Yemen",
	"YT": "Mayotte",
	"ZA": "South Africa",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
}
